name: Release Build

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.3"

      - name: Build Go binary
        run: |
          go build -ldflags="-s -w -H=windowsgui" -o phpman-win.exe
          tar -czvf phpman-win.tar.gz phpman-win.exe
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            phpman-win.exe
            phpman-win.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}